server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:devmind}
    username: ${MYSQL_USERNAME:devmind}
    password: ${MYSQL_PASSWORD:devmind_local_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always


logging:
  pattern:
    console: "%d{ISO8601} %-5level [%X{correlationId}] %logger{36} - %msg%n"
