apiVersion: v1
kind: ConfigMap
metadata: { name: devmind-config, namespace: devmind }
data:
  AI_PROVIDER: "ollama"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "devmind"
  OLLAMA_BASE_URL: "http://ollama:11434"
  QDRANT_URL: "http://qdrant:6333"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  REPOSITORY_SERVICE_URL: "http://repository-service:8082"


