apiVersion: v1
kind: Secret
metadata:
  name: devmind-secrets
  namespace: devmind
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${}
  MYSQL_USERNAME: ${MYSQL_USERNAME}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
  INTERNAL_API_KEY: ${INTERNAL_API_KEY}
  GITHUB_CLIENT_ID : ${GITHUB_CLIENT_ID}
  GITHUB_CLIENT_SECRET : ${GITHUB_CLIENT_SECRET}