server:
  port: 8082

spring:
  application:
    name: repository-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:devmind}
    username: ${MYSQL_USERNAME:devmind}
    password: ${MYSQL_PASSWORD:devmind_local_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: repository_flyway_schema_history
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: repository-service
      auto-offset-reset: earliest

devmind:
  auth-service-url: ${AUTH_SERVICE_URL:http://auth-service:8081}
  internal-api-key: ${INTERNAL_API_KEY:replace_with_a_shared_internal_secret}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always


logging:
  pattern:
    console: "%d{ISO8601} %-5level [%X{correlationId}] %logger{36} - %msg%n"
