import PageContainer from '../components/PageContainer.jsx';

export default function PrivacyPage() {
    return (
        <PageContainer>
            <h1>Privacy Notice</h1>
            <p><em>Last updated: //</em></p>

            <p>
                This notice explains what personal data DevMind (&quot;we&quot;, &quot;us&quot;) collects, why, and the rights
                you have under India&apos;s Digital Personal Data Protection Act, 2023 (&quot;DPDP Act&quot;).
            </p>

            <h2>Who we are</h2>
            <p>
                It is a personal project made for understanding.
            </p>

            <h2>What personal data we collect, and why</h2>
            <table>
                <thead>
                <tr><th>Data</th><th>Source</th><th>Purpose</th><th>Retention</th></tr>
                </thead>
                <tbody>
                <tr>
                    <td>Name, email, password (hashed)</td>
                    <td>You, at registration</td>
                    <td>Create and secure your account</td>

                </tr>
                <tr>
                    <td>Name, email, GitHub username, avatar</td>
                    <td>GitHub, via OAuth login (if you sign in with GitHub)</td>
                    <td>Authenticate you; link your GitHub identity to your DevMind account</td>

                </tr>
                <tr>
                    <td>GitHub repository content (code, commits, pull requests) you connect</td>
                    <td>GitHub API, with your authorization</td>
                    <td>Index and search your code, generate AI answers/PR reviews/documentation</td>
                </tr>
                <tr>
                    <td>Session tokens (JWT access token, httpOnly refresh cookie)</td>
                    <td>Generated by us at login</td>
                    <td>Keep you signed in</td>
                    <td>Access token: short-lived, held in memory only. Refresh token: long-lived</td>
                </tr>
                <tr>
                    <td>Usage data (which repos you query, PR review activity, AI usage counts)</td>
                    <td>Generated as you use the product</td>
                    <td>Show you the analytics dashboard; internal product improvement</td>

                </tr>
                <tr>
                    <td>Team-member names/emails/roles</td>
                    <td>Entered by an account admin in Settings</td>
                    <td>Team access control</td>

                </tr>
                <tr>
                    <td>Commit author names and emails, pull request metadata</td>
                    <td>Pulled from GitHub as part of a connected repository&apos;s history</td>
                    <td>Power repository analytics, AI code search/chat, PR review</td>

                </tr>
                </tbody>
            </table>

            <p>
                <em>[ENGINEERING NOTE — not for publication: this table reflects every personal-data-holding
                    database table found in the codebase as of this audit (auth-service: User, RefreshToken;
                    repository-service: Repository, RepoCommit, RepoPullRequest; analysis-service: PrReview,
                    PrReviewFinding). If new tables are added later, this table needs updating to match.]</em>
            </p>

            <h2>Third parties</h2>
            <ul>
                <li><strong>GitHub</strong> — identity provider (OAuth) and source of repository data, including commit author names/emails. See GitHub&apos;s own privacy policy.</li>
                <li>
                    <strong>No email, SMS, or payment provider is used.</strong> Confirmed against the
                    infrastructure configuration — there is nothing to disclose here.
                </li>
                <li>
                    The following are self-hosted infrastructure, not third-party data processors in the
                    traditional sense (nothing leaves our own servers), but are listed for completeness:
                    object storage (MinIO), search indexing (OpenSearch), and observability/metrics
                    (Prometheus, Grafana, Jaeger — used to monitor system performance, not to profile users).

                </li>
                <li>
                    AI processing (embeddings, chat answers, PR review generation) runs on a self-hosted
                    Ollama instance — no repository content or query text is sent to an external AI API
                    provider as of this audit.
                </li>
            </ul>

            <h2>Your rights under the DPDP Act</h2>
            <p>You have the right to:</p>
            <ul>
                <li><strong>Access</strong> — get a copy of the personal data we hold about you.</li>
                <li><strong>Correct</strong> — fix inaccurate or incomplete data.</li>
                <li><strong>Erase</strong> — request deletion of your data, subject to legal retention requirements.</li>
                <li><strong>Withdraw consent</strong> — for anything you opted into, at any time, as easily as you gave it.</li>
                <li><strong>Grievance redressal</strong> — raise a complaint if you believe we have mishandled your data.</li>
            </ul>
            <p>
                To exercise any of these, use our <a href="/data-rights">Data Rights Request form</a>, or contact
                our Grievance Officer directly (see footer).
            </p>

            <h2>Grievance Officer</h2>

        </PageContainer>
    );
}